@baseUrl = http://localhost:5168

###
GET {{baseUrl}}/users

### 
# @name createuser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com"
}

###
# @name getcreateduser 
GET {{baseUrl}}/users/{{createuser.response.body.id}}

###
# @name createpost
POST {{baseUrl}}/posts
Content-Type: application/json

{
    "title": "My thrd post",
    "body": "This is my thrd post",
    "userId": "ec58b5e2-2a4b-4869-a9e0-86fd5e595b4c"
}
###
# @name getposts
GET {{baseUrl}}/posts
Content-Type: application/json

###
# @name addwatcher
PUT {{baseUrl}}/posts/{{createpost.response.body.id}}/addwatcher/{{createuser.response.body.id}}

###
# @name getfirstpost
GET {{baseUrl}}/posts/{{createpost.response.body.id}}
